# Generated by Django 5.2 on 2025-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='carbooking',
            name='dropoff_location',
            field=models.CharField(default=-1, max_length=255),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='name',
            field=models.CharField(default=-1, max_length=100),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='phone',
            field=models.CharField(default=-1, max_length=20),
        ),
    ]
