# Generated by Django 5.2 on 2025-04-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabBooking', '0002_taxicar_carbooking_dropoff_location_carbooking_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='name',
            new_name='username',
        ),
    ]
