# Generated by Django 5.2 on 2025-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabBooking', '0003_rename_name_carbooking_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxicar',
            name='driver_license',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxicar',
            name='driver_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxicar',
            name='driver_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxicar',
            name='driver_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
