# Generated by Django 5.2 on 2025-04-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabBooking', '0004_taxicar_driver_license_taxicar_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='taxi_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabBooking.taxicar'),
        ),
    ]
