# Generated by Django 5.2 on 2025-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelBooking', '0002_property_owner_alter_booking_rooms_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('AC', 'AC Room'), ('NON_AC', 'Non-AC Room'), ('DUPLEX', 'Duplex Suite'), ('TRIPLEX', 'Triplex Suite'), ('DELUXE', 'Deluxe Room'), ('STANDARD', 'Standard Room')], default='STANDARD', max_length=20),
        ),
    ]
