# Generated by Django 5.2 on 2025-04-17 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelBooking', '0003_booking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
