# Generated by Django 5.2 on 2025-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelBooking', '0004_property_room_types_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='room_types',
            field=models.JSONField(default=list),
        ),
    ]
